"""
Markdown PR Report Formatter

Produces a GitHub-ready PR comment with blast radius risk score,
visual impact tree, synthesized test code, and recommended patch diff.
"""
from models.analysis import AnalysisReport

RISK_EMOJI = {
    "low": "🟢",
    "medium": "🟡",
    "high": "🟠",
    "critical": "🔴",
}


def format_markdown_report(report: AnalysisReport) -> str:
    br = report.blast_radius
    emoji = RISK_EMOJI.get(br.risk_level.value, "⚪")
    lines: list[str] = []

    lines.append(f"## 🧪 Astria AI — Blast Radius Report")
    lines.append(f"**PR:** {report.pr_title}")
    lines.append("")
    lines.append(f"### Risk Assessment {emoji}")
    lines.append(
        f"| Metric | Value |"
        "\n| --- | --- |"
        f"\n| Risk Level | **{br.risk_level.value.upper()}** |"
        f"\n| Risk Score | {br.risk_score}/100 |"
        f"\n| Impacted Routes | {len(br.impacted_routes)} |"
        f"\n| Impacted Models | {len(br.impacted_models)} |"
    )
    lines.append("")
    lines.append(f"> {br.summary}")
    lines.append("")

    # Impact tree
    lines.append("### 🌐 Impact Tree")
    lines.append("```")
    lines.append("Modified Code")
    for route in br.impacted_routes[:8]:
        lines.append(f"  └── [{route.method}] {route.path}  ({route.service})")
        lines.append(f"       ↳ {route.risk_reason}")
    lines.append("```")
    lines.append("")

    # Fuzz payloads summary
    lines.append("### 🎯 Edge-Case Payloads Generated")
    for p in report.fuzz_payloads.payloads[:5]:
        lines.append(f"- **{p.name}**: {p.description}")
    lines.append("")

    # Synthesized test
    lines.append("### 🧬 Synthesized Regression Test")
    lang = "python" if report.synthesized_test.framework == "pytest" else "typescript"
    lines.append(f"```{lang}")
    # Show first 60 lines of the test file
    test_preview = "\n".join(report.synthesized_test.content.splitlines()[:60])
    lines.append(test_preview)
    if len(report.synthesized_test.content.splitlines()) > 60:
        lines.append("# ... (truncated) see full test file in artifacts")
    lines.append("```")
    lines.append("")

    # Test execution results
    if report.test_execution:
        te = report.test_execution
        status = "✅ All tests passed" if te.success else f"❌ {te.failed} test(s) failed"
        lines.append("### ⚡ Test Execution Results")
        lines.append(f"**{status}**")
        lines.append(
            f"| Passed | Failed | Errors |"
            "\n| --- | --- | --- |"
            f"\n| {te.passed} | {te.failed} | {te.errors} |"
        )
        if te.regressions_caught:
            lines.append("")
            lines.append("**Regressions caught:**")
            for r in te.regressions_caught:
                lines.append(f"- `{r}`")
        lines.append("")

    # Remediation patch
    if report.remediation:
        rm = report.remediation
        lines.append("### 🔧 Recommended 1-Click Patch")
        lines.append(f"**File:** `{rm.file_path}`")
        lines.append(f"**Explanation:** {rm.explanation}")
        lines.append("```diff")
        for orig_line in rm.original_snippet.splitlines():
            lines.append(f"- {orig_line}")
        for new_line in rm.patched_snippet.splitlines():
            lines.append(f"+ {new_line}")
        lines.append("```")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [Astria AI](https://github.com) using IBM Granite on watsonx.ai*")

    return "\n".join(lines)
