/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnotherPageRouteImport } from './routes/anotherPage'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AnalysisIdRouteImport } from './routes/analysis.$id'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardManualRouteImport } from './routes/dashboard.manual'
import { Route as DashboardOwnerRepoRouteImport } from './routes/dashboard.$owner.$repo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnotherPageRoute = AnotherPageRouteImport.update({
  id: '/anotherPage',
  path: '/anotherPage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIdRoute = AnalysisIdRouteImport.update({
  id: '/analysis/$id',
  path: '/analysis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardManualRoute = DashboardManualRouteImport.update({
  id: '/dashboard/manual',
  path: '/dashboard/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOwnerRepoRoute = DashboardOwnerRepoRouteImport.update({
  id: '/dashboard/$owner/$repo',
  path: '/dashboard/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/login': typeof LoginRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/dashboard/manual': typeof DashboardManualRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$owner/$repo': typeof DashboardOwnerRepoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/login': typeof LoginRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/dashboard/manual': typeof DashboardManualRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/$owner/$repo': typeof DashboardOwnerRepoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/login': typeof LoginRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/dashboard/manual': typeof DashboardManualRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$owner/$repo': typeof DashboardOwnerRepoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anotherPage'
    | '/login'
    | '/analysis/$id'
    | '/dashboard/manual'
    | '/dashboard/'
    | '/dashboard/$owner/$repo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anotherPage'
    | '/login'
    | '/analysis/$id'
    | '/dashboard/manual'
    | '/dashboard'
    | '/dashboard/$owner/$repo'
  id:
    | '__root__'
    | '/'
    | '/anotherPage'
    | '/login'
    | '/analysis/$id'
    | '/dashboard/manual'
    | '/dashboard/'
    | '/dashboard/$owner/$repo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnotherPageRoute: typeof AnotherPageRoute
  LoginRoute: typeof LoginRoute
  AnalysisIdRoute: typeof AnalysisIdRoute
  DashboardManualRoute: typeof DashboardManualRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardOwnerRepoRoute: typeof DashboardOwnerRepoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anotherPage': {
      id: '/anotherPage'
      path: '/anotherPage'
      fullPath: '/anotherPage'
      preLoaderRoute: typeof AnotherPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$id': {
      id: '/analysis/$id'
      path: '/analysis/$id'
      fullPath: '/analysis/$id'
      preLoaderRoute: typeof AnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/manual': {
      id: '/dashboard/manual'
      path: '/dashboard/manual'
      fullPath: '/dashboard/manual'
      preLoaderRoute: typeof DashboardManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$owner/$repo': {
      id: '/dashboard/$owner/$repo'
      path: '/dashboard/$owner/$repo'
      fullPath: '/dashboard/$owner/$repo'
      preLoaderRoute: typeof DashboardOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnotherPageRoute: AnotherPageRoute,
  LoginRoute: LoginRoute,
  AnalysisIdRoute: AnalysisIdRoute,
  DashboardManualRoute: DashboardManualRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardOwnerRepoRoute: DashboardOwnerRepoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
